display:
  messages:
    reloaded: "Configuration reloaded"

    game:
      showing_theme: "%name% >> %theme%<n>"
      showing_build: "%name% >> ..."
      start_build: "<br><color:#d68fff>|</color> нᴀчᴀло стᴘоитᴇльствᴀ!<br><color:#d68fff>|</color> тᴇмᴀ для постᴘойки: <gradient:#654aff:#ce47ff>%theme%</gradient><br>"
      text_completed: "<br><color:#d68fff>|</color> вы нᴀписᴀли: <gradient:#654aff:#ce47ff>%theme%</gradient><br><color:#d68fff>|</color> ожидᴀйтᴇ.<br>"
      build_completed: "<br><color:#d68fff>|</color> вы зᴀвᴇᴘшилки постᴘойкʏ, ожидᴀйтᴇ дᴘʏгих ʏчᴀстников<br>"
      start_texting: "<br><color:#d68fff>|</color> пᴘидʏмᴀйтᴇ тᴇмʏ для постᴘойки!<br><color:#d68fff>|</color> пᴘимᴇᴘ: <gradient:#654aff:#ce47ff>ᴘозовый гʏсь смотᴘит в окно</gradient><br>"
      describe_build: "<br><color:#d68fff>|</color> опишитᴇ постᴘойкʏ, котоᴘʏю видитᴇ!<br>"
  bars:
    lobby_waiting: "Ожидание лидера лобби. В лобби %lobby%/14"
    lobby_starting: "Начало игры через %countdown%... (%lobby%/14)"
  title:
    black: "ꐐ"
  invs:
    describe:
      title: ""
    lobby:
      title: "<white>ꐮꐮꐫꐑ</white>"
    main:
      title: "<white>ꐮꐮꐫꑼ</white>"

map:
  world: overworld
  rooms:
    - "room:::point:-250:409:213:::cuboid::point:-262:432:225::point:-238:408:201"
    - "room:::point:-250:409:186:::cuboid::point:-262:432:199::point:-238:408:175"